/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PublisherController;
import javax.swing.JOptionPane;
import model.Publisher;

/**
 *
 * @author thoni
 */
public class TelaAlterarPublisher2 extends javax.swing.JFrame {

    protected Publisher selectedPublisher;

    /**
     * Creates new form TelaAlterarPublisher2
     */
    public TelaAlterarPublisher2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelExlcuirAutor2 = new javax.swing.JPanel();
        jButtonAlterarEditora = new javax.swing.JButton();
        jButtonCancelar2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelAlterarEditoraSelecionada = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldAlterarEditoraNovoNome = new javax.swing.JTextField();
        jTextFieldAlterarEditoraNovoUrl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("ALTERAR EDITORA");

        jPanelExlcuirAutor2.setBackground(new java.awt.Color(153, 153, 153));

        jButtonAlterarEditora.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButtonAlterarEditora.setText("Alterar");
        jButtonAlterarEditora.setToolTipText("");
        jButtonAlterarEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarEditoraActionPerformed(evt);
            }
        });

        jButtonCancelar2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButtonCancelar2.setText("Cancelar");
        jButtonCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setText("EDITORA SELECIONADA:");

        jLabelAlterarEditoraSelecionada.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabelAlterarEditoraSelecionada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAlterarEditoraSelecionada.setText("Nome: Thoni; Sobrenome: Miguel");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Novo Nome:");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("Novo URL:");

        jTextFieldAlterarEditoraNovoNome.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextFieldAlterarEditoraNovoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlterarEditoraNovoNomeActionPerformed(evt);
            }
        });

        jTextFieldAlterarEditoraNovoUrl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelExlcuirAutor2Layout = new javax.swing.GroupLayout(jPanelExlcuirAutor2);
        jPanelExlcuirAutor2.setLayout(jPanelExlcuirAutor2Layout);
        jPanelExlcuirAutor2Layout.setHorizontalGroup(
            jPanelExlcuirAutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExlcuirAutor2Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(jPanelExlcuirAutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanelExlcuirAutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldAlterarEditoraNovoNome)
                    .addComponent(jTextFieldAlterarEditoraNovoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelExlcuirAutor2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButtonCancelar2)
                .addGap(425, 425, 425)
                .addComponent(jButtonAlterarEditora)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExlcuirAutor2Layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addGroup(jPanelExlcuirAutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAlterarEditoraSelecionada)
                    .addComponent(jLabel9))
                .addGap(192, 192, 192))
        );
        jPanelExlcuirAutor2Layout.setVerticalGroup(
            jPanelExlcuirAutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExlcuirAutor2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabelAlterarEditoraSelecionada)
                .addGap(46, 46, 46)
                .addGroup(jPanelExlcuirAutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldAlterarEditoraNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanelExlcuirAutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldAlterarEditoraNovoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(jPanelExlcuirAutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterarEditora)
                    .addComponent(jButtonCancelar2))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelExlcuirAutor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanelExlcuirAutor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarEditoraActionPerformed
        // TODO add your handling code here:
        PublisherController pubC = new PublisherController();
        String nome = jTextFieldAlterarEditoraNovoNome.getText();
        String url = jTextFieldAlterarEditoraNovoUrl.getText();
        boolean situacao = pubC.update(nome, url, selectedPublisher);
        if (situacao) {
            JOptionPane.showMessageDialog(null, "Os valores foram alterados com sucesso!");
            this.dispose();
            new TelaAlterarPublisher().setVisible(true);
        } else if (situacao == false) {
            JOptionPane.showMessageDialog(null, "Ops... parece que um erro aconteceu!");
        }

    }//GEN-LAST:event_jButtonAlterarEditoraActionPerformed

    private void jButtonCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_jButtonCancelar2ActionPerformed

    private void jTextFieldAlterarEditoraNovoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlterarEditoraNovoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlterarEditoraNovoNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarPublisher2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarPublisher2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarPublisher2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarPublisher2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarPublisher2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAlterarEditora;
    private javax.swing.JButton jButtonCancelar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelAlterarEditoraSelecionada;
    private javax.swing.JPanel jPanelExlcuirAutor2;
    private javax.swing.JTextField jTextFieldAlterarEditoraNovoNome;
    private javax.swing.JTextField jTextFieldAlterarEditoraNovoUrl;
    // End of variables declaration//GEN-END:variables
}
