/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AuthorController;
import javax.swing.JOptionPane;
import model.Author;

/**
 *
 * @author thoni
 */
public class TelaAlterarAuthor2 extends javax.swing.JFrame {

    protected Author author = null;

    /**
     * Creates new form TelaAlterarAuthor2
     */
    public TelaAlterarAuthor2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelExlcuirAutor = new javax.swing.JPanel();
        jButtonAlterarAutor = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelAlterarAutorSelecionado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAlterarAutorNovoNome = new javax.swing.JTextField();
        jTextFieldAlterarAutorNovoSobrenome = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("ALTERAR AUTOR");

        jPanelExlcuirAutor.setBackground(new java.awt.Color(153, 153, 153));

        jButtonAlterarAutor.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButtonAlterarAutor.setText("Alterar");
        jButtonAlterarAutor.setToolTipText("");
        jButtonAlterarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarAutorActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("AUTOR SELECIONADO:");

        jLabelAlterarAutorSelecionado.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabelAlterarAutorSelecionado.setText("Nome: Thoni; Sobrenome: Miguel");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Novo Nome:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Novo Sobrenome:");

        jTextFieldAlterarAutorNovoNome.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextFieldAlterarAutorNovoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlterarAutorNovoNomeActionPerformed(evt);
            }
        });

        jTextFieldAlterarAutorNovoSobrenome.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelExlcuirAutorLayout = new javax.swing.GroupLayout(jPanelExlcuirAutor);
        jPanelExlcuirAutor.setLayout(jPanelExlcuirAutorLayout);
        jPanelExlcuirAutorLayout.setHorizontalGroup(
            jPanelExlcuirAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExlcuirAutorLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(jPanelExlcuirAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanelExlcuirAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldAlterarAutorNovoNome)
                    .addComponent(jTextFieldAlterarAutorNovoSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelExlcuirAutorLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButtonCancelar)
                .addGap(425, 425, 425)
                .addComponent(jButtonAlterarAutor)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExlcuirAutorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabelAlterarAutorSelecionado)
                .addGap(122, 122, 122))
        );
        jPanelExlcuirAutorLayout.setVerticalGroup(
            jPanelExlcuirAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExlcuirAutorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelExlcuirAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelAlterarAutorSelecionado))
                .addGap(87, 87, 87)
                .addGroup(jPanelExlcuirAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldAlterarAutorNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanelExlcuirAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAlterarAutorNovoSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(jPanelExlcuirAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterarAutor)
                    .addComponent(jButtonCancelar))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelExlcuirAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanelExlcuirAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarAutorActionPerformed
        // TODO add your handling code here:
        AuthorController authorController = new AuthorController();
        String nome = jTextFieldAlterarAutorNovoNome.getText();
        String sobrenome = jTextFieldAlterarAutorNovoSobrenome.getText();
        Author newAuthor = new Author();
        newAuthor.setName(nome);
        newAuthor.setfName(sobrenome);
        try {
            boolean situacao = authorController.updateAuthor(newAuthor, this.author);
            if (situacao) {
                JOptionPane.showMessageDialog(null, "Elemento atualizado com sucesso!");
                this.dispose();
                new TelaAlterarAuthor().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Os valores inseridos estão incorretos. Tente novamente!");
            }
        }catch(Exception e){
            System.out.println("Oh nao :( O seguinte erro aconteceu: " + e.getMessage());
        }


    }//GEN-LAST:event_jButtonAlterarAutorActionPerformed

    private void jTextFieldAlterarAutorNovoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlterarAutorNovoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlterarAutorNovoNomeActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarAuthor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarAuthor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarAuthor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarAuthor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarAuthor2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAlterarAutor;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabelAlterarAutorSelecionado;
    private javax.swing.JPanel jPanelExlcuirAutor;
    private javax.swing.JTextField jTextFieldAlterarAutorNovoNome;
    private javax.swing.JTextField jTextFieldAlterarAutorNovoSobrenome;
    // End of variables declaration//GEN-END:variables
}
