/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BookController;
import controller.PublisherController;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Publisher;

/**
 *
 * @author thoni
 */
public class TelaExcluirPublisher extends javax.swing.JFrame {

    /**
     * Creates new form TelaExcluirPublisher
     */
    public TelaExcluirPublisher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelExlcuirAutor1 = new javax.swing.JPanel();
        jButtonDeletarPublisher = new javax.swing.JButton();
        jButtonVoltar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListExcluirEditora = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("EXCLUIR EDITORA");

        jPanelExlcuirAutor1.setBackground(new java.awt.Color(153, 153, 153));

        jButtonDeletarPublisher.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButtonDeletarPublisher.setText("Deletar");
        jButtonDeletarPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarPublisherActionPerformed(evt);
            }
        });

        jButtonVoltar1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButtonVoltar1.setText("Voltar");
        jButtonVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltar1ActionPerformed(evt);
            }
        });

        jListExcluirEditora.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jListExcluirEditora.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jListExcluirEditora);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selecione a editora que deseja remover, e logo após clique em DELETAR:");

        javax.swing.GroupLayout jPanelExlcuirAutor1Layout = new javax.swing.GroupLayout(jPanelExlcuirAutor1);
        jPanelExlcuirAutor1.setLayout(jPanelExlcuirAutor1Layout);
        jPanelExlcuirAutor1Layout.setHorizontalGroup(
            jPanelExlcuirAutor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExlcuirAutor1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanelExlcuirAutor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExlcuirAutor1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(190, Short.MAX_VALUE))
                    .addGroup(jPanelExlcuirAutor1Layout.createSequentialGroup()
                        .addGroup(jPanelExlcuirAutor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanelExlcuirAutor1Layout.createSequentialGroup()
                                .addComponent(jButtonVoltar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDeletarPublisher)))
                        .addGap(75, 75, 75))))
        );
        jPanelExlcuirAutor1Layout.setVerticalGroup(
            jPanelExlcuirAutor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExlcuirAutor1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanelExlcuirAutor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeletarPublisher)
                    .addComponent(jButtonVoltar1))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelExlcuirAutor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanelExlcuirAutor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeletarPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarPublisherActionPerformed
        // TODO add your handling code here:
        BookController bookC = new BookController();
        PublisherController pubC = new PublisherController();
        Object temp = jListExcluirEditora.getSelectedValue();
        if(temp == null){
            JOptionPane.showMessageDialog(null, "Selecione um valor!", "Aviso", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Publisher pub = (Publisher) temp;
        List<String> list = bookC.searchBookFromPublisher(pub);
        pubC.delete(pub, list);
        this.dispose();
        new TelaPrincipal().setVisible(true);
        
    }//GEN-LAST:event_jButtonDeletarPublisherActionPerformed

    private void jButtonVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_jButtonVoltar1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        PublisherController pubC = new PublisherController();
        List<Publisher> list = pubC.findAll();
        DefaultListModel model = new DefaultListModel();
        for(Publisher p : list){
            model.addElement(p);
        }
        jListExcluirEditora.setModel(model);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExcluirPublisher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeletarAutor;
    private javax.swing.JButton jButtonDeletarPublisher;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JButton jButtonVoltar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListExcluirEditora;
    private javax.swing.JList<String> jListExcluirLivro;
    private javax.swing.JPanel jPanelExlcuirAutor;
    private javax.swing.JPanel jPanelExlcuirAutor1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
