/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BookController;
import javax.swing.JOptionPane;

/**
 *
 * @author thoni
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTelaPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBarTelaPrincipal = new javax.swing.JMenuBar();
        jMenuBusca = new javax.swing.JMenu();
        jMenuItemBuscarAutor = new javax.swing.JMenuItem();
        jMenuItemBuscarLivro = new javax.swing.JMenuItem();
        jMenuItemBuscarEditora = new javax.swing.JMenuItem();
        jMenuAlterar = new javax.swing.JMenu();
        jMenuItemAlterarAutor = new javax.swing.JMenuItem();
        jMenuItemAlterarLivro = new javax.swing.JMenuItem();
        jMenuItemAlterarEditora = new javax.swing.JMenuItem();
        jMenuIncluir = new javax.swing.JMenu();
        jMenuItemIncluirAutor = new javax.swing.JMenuItem();
        jMenuItemIncluirLivro = new javax.swing.JMenuItem();
        jMenuItemIncluirEditora = new javax.swing.JMenuItem();
        jMenuExcluir = new javax.swing.JMenu();
        jMenuItemExcluirAutor = new javax.swing.JMenuItem();
        jMenuItemExcluirLivro = new javax.swing.JMenuItem();
        jMenuItemExcluirEditora = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Amazonia");
        setResizable(false);

        jPanelTelaPrincipal.setBackground(new java.awt.Color(153, 153, 153));
        jPanelTelaPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("BIBLIOTECA");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("VIRTUAL");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("AMAZÔNIA");

        javax.swing.GroupLayout jPanelTelaPrincipalLayout = new javax.swing.GroupLayout(jPanelTelaPrincipal);
        jPanelTelaPrincipal.setLayout(jPanelTelaPrincipalLayout);
        jPanelTelaPrincipalLayout.setHorizontalGroup(
            jPanelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaPrincipalLayout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addGroup(jPanelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanelTelaPrincipalLayout.setVerticalGroup(
            jPanelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaPrincipalLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(128, 128, 128))
        );

        jMenuBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/search.png"))); // NOI18N
        jMenuBusca.setText("Buscar");
        jMenuBusca.setMargin(new java.awt.Insets(0, 5, 0, 5));

        jMenuItemBuscarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/right-arrow.png"))); // NOI18N
        jMenuItemBuscarAutor.setText("Autor");
        jMenuItemBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarAutorActionPerformed(evt);
            }
        });
        jMenuBusca.add(jMenuItemBuscarAutor);

        jMenuItemBuscarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/right-arrow.png"))); // NOI18N
        jMenuItemBuscarLivro.setText("Livro");
        jMenuItemBuscarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarLivroActionPerformed(evt);
            }
        });
        jMenuBusca.add(jMenuItemBuscarLivro);

        jMenuItemBuscarEditora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/right-arrow.png"))); // NOI18N
        jMenuItemBuscarEditora.setText("Editora");
        jMenuItemBuscarEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarEditoraActionPerformed(evt);
            }
        });
        jMenuBusca.add(jMenuItemBuscarEditora);

        jMenuBarTelaPrincipal.add(jMenuBusca);

        jMenuAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/edit.png"))); // NOI18N
        jMenuAlterar.setText("Alterar");

        jMenuItemAlterarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/right-arrow.png"))); // NOI18N
        jMenuItemAlterarAutor.setText("Autor");
        jMenuItemAlterarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarAutorActionPerformed(evt);
            }
        });
        jMenuAlterar.add(jMenuItemAlterarAutor);

        jMenuItemAlterarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/right-arrow.png"))); // NOI18N
        jMenuItemAlterarLivro.setText("Livro");
        jMenuItemAlterarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarLivroActionPerformed(evt);
            }
        });
        jMenuAlterar.add(jMenuItemAlterarLivro);

        jMenuItemAlterarEditora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/right-arrow.png"))); // NOI18N
        jMenuItemAlterarEditora.setText("Editora");
        jMenuItemAlterarEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarEditoraActionPerformed(evt);
            }
        });
        jMenuAlterar.add(jMenuItemAlterarEditora);

        jMenuBarTelaPrincipal.add(jMenuAlterar);

        jMenuIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/add.png"))); // NOI18N
        jMenuIncluir.setText("Incluir");

        jMenuItemIncluirAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/right-arrow.png"))); // NOI18N
        jMenuItemIncluirAutor.setText("Autor");
        jMenuItemIncluirAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIncluirAutorActionPerformed(evt);
            }
        });
        jMenuIncluir.add(jMenuItemIncluirAutor);

        jMenuItemIncluirLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/right-arrow.png"))); // NOI18N
        jMenuItemIncluirLivro.setText("Livro");
        jMenuItemIncluirLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIncluirLivroActionPerformed(evt);
            }
        });
        jMenuIncluir.add(jMenuItemIncluirLivro);

        jMenuItemIncluirEditora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/right-arrow.png"))); // NOI18N
        jMenuItemIncluirEditora.setText("Editora");
        jMenuItemIncluirEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIncluirEditoraActionPerformed(evt);
            }
        });
        jMenuIncluir.add(jMenuItemIncluirEditora);

        jMenuBarTelaPrincipal.add(jMenuIncluir);

        jMenuExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/delete.png"))); // NOI18N
        jMenuExcluir.setText("Excluir");
        jMenuExcluir.setMargin(new java.awt.Insets(0, 5, 0, 5));

        jMenuItemExcluirAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/right-arrow.png"))); // NOI18N
        jMenuItemExcluirAutor.setText("Autor");
        jMenuItemExcluirAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirAutorActionPerformed(evt);
            }
        });
        jMenuExcluir.add(jMenuItemExcluirAutor);

        jMenuItemExcluirLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/right-arrow.png"))); // NOI18N
        jMenuItemExcluirLivro.setText("Livro");
        jMenuItemExcluirLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirLivroActionPerformed(evt);
            }
        });
        jMenuExcluir.add(jMenuItemExcluirLivro);

        jMenuItemExcluirEditora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/right-arrow.png"))); // NOI18N
        jMenuItemExcluirEditora.setText("Editora");
        jMenuItemExcluirEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirEditoraActionPerformed(evt);
            }
        });
        jMenuExcluir.add(jMenuItemExcluirEditora);

        jMenuBarTelaPrincipal.add(jMenuExcluir);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaPrincipal/exit.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBarTelaPrincipal.add(jMenuSair);

        setJMenuBar(jMenuBarTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jPanelTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBuscarEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarEditoraActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaBuscarPublisher().setVisible(true);
    }//GEN-LAST:event_jMenuItemBuscarEditoraActionPerformed

    private void jMenuItemAlterarEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarEditoraActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaAlterarPublisher().setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarEditoraActionPerformed

    private void jMenuItemAlterarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarLivroActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaAlterarBook().setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarLivroActionPerformed

    private void jMenuItemIncluirLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIncluirLivroActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaIncluirBook().setVisible(true);
    }//GEN-LAST:event_jMenuItemIncluirLivroActionPerformed

    private void jMenuItemIncluirEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIncluirEditoraActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaIncluirPublisher().setVisible(true);
    }//GEN-LAST:event_jMenuItemIncluirEditoraActionPerformed

    private void jMenuItemExcluirLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirLivroActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaExcluirBook().setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirLivroActionPerformed

    private void jMenuItemExcluirEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirEditoraActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaExcluirPublisher().setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirEditoraActionPerformed

    private void jMenuItemExcluirAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirAutorActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaExcluirAuthor().setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirAutorActionPerformed

    private void jMenuItemIncluirAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIncluirAutorActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaIncluirAuthor().setVisible(true);
    }//GEN-LAST:event_jMenuItemIncluirAutorActionPerformed

    private void jMenuItemBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarAutorActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaBuscarAuthor().setVisible(true);
    }//GEN-LAST:event_jMenuItemBuscarAutorActionPerformed

    private void jMenuItemAlterarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarAutorActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaAlterarAuthor().setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarAutorActionPerformed

    private void jMenuItemBuscarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarLivroActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaBuscarBook().setVisible(true);
    }//GEN-LAST:event_jMenuItemBuscarLivroActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_jMenuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenuAlterar;
    private javax.swing.JMenuBar jMenuBarTelaPrincipal;
    private javax.swing.JMenu jMenuBusca;
    private javax.swing.JMenu jMenuExcluir;
    private javax.swing.JMenu jMenuIncluir;
    private javax.swing.JMenuItem jMenuItemAlterarAutor;
    private javax.swing.JMenuItem jMenuItemAlterarEditora;
    private javax.swing.JMenuItem jMenuItemAlterarLivro;
    private javax.swing.JMenuItem jMenuItemBuscarAutor;
    private javax.swing.JMenuItem jMenuItemBuscarEditora;
    private javax.swing.JMenuItem jMenuItemBuscarLivro;
    private javax.swing.JMenuItem jMenuItemExcluirAutor;
    private javax.swing.JMenuItem jMenuItemExcluirEditora;
    private javax.swing.JMenuItem jMenuItemExcluirLivro;
    private javax.swing.JMenuItem jMenuItemIncluirAutor;
    private javax.swing.JMenuItem jMenuItemIncluirEditora;
    private javax.swing.JMenuItem jMenuItemIncluirLivro;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
